<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNjBQTti\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNjBQTti/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNjBQTti.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNjBQTti\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNjBQTti\App_KernelDevDebugContainer([
    'container.build_hash' => 'NjBQTti',
    'container.build_id' => 'f6b5bf89',
    'container.build_time' => 1761126930,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNjBQTti');
