<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGLvuviJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGLvuviJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGLvuviJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGLvuviJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGLvuviJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'GLvuviJ',
    'container.build_id' => 'e73d1344',
    'container.build_time' => 1761062036,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGLvuviJ');
