<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.544b3ba4.js',
                '/build/292.87b3165c.js',
                '/build/app.c8d9d981.js',
            ],
            'css' => [
                '/build/292.cc6c18cc.css',
                '/build/app.5c8205b6.css',
            ],
        ],
    ],
],

]];
